name: Ejecutando Tests # El nombre no importa, es una string

# Cada cuando quiero que se ejecute este workflow
on: 
  push: 
    branches: ["develop"] # Es el nombre de las ramas
 # Ejecute cada cierta cantidad de tiempo
 # schedule:
    #- cron: '' # Lunes a las 8am
  workflow_dispatch: # Permitiendo que esta se dispare desde Github Actions

jobs: # se pueden definir n cantidad de Jobs

  test: # El nombre no importa
    runs-on: ubuntu-latest # El runner o ambiente en el que se va a ejecutar
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup NodeJs v20 # El nombre es una string
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'
      
      - name: Instalar Dependencias
        run: npm ci # Este comando no es necesario que exista en mi package.json, es uso exclusivo de CI

      - name: Ejecutar Pruebas Unitarias
        run: npm run test # Este comando debe de existir en mi package.json
  
  lint: 
    needs: [test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs v20 # El nombre es una string
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'
      - name: Instalar Dependencias
        run: npm ci # Este comando no es necesario que exista en mi package.json, es uso exclusivo de CI

      - name: Ejecutar Linting
        run: npm run lint # Este comando debe de existir en mi package.json
  
  